# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a86c6e648e3a820087feb6e98a9b22a58b428b10781b36bde990e011dceafb3aeeafeb19f360c988983c7836f0f5565631123e3ab6cd240802c145c1fda7dbd

test:
  secret_key_base: 1c0d8481ea6c49f60dba8aa7628505a5c4a241c15d6dd544fa37c13714669776b5911452cdbe04a12e41712c35fcaba1571efb995f4388c6b1ded1fdc526fff2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
